window.MUNICIPAL_ROLES = [
  {
    id: 'ACT-01',
    title: 'Municipal Commissioner',
    category: 'Leadership',
    description: 'Executive Sponsor & Administrative Head of Ahmedabad Municipal Corporation.',
    authorityLevel: 'Executive',
    tone: 'purple',
  },
  {
    id: 'ACT-02',
    title: 'Data Protection Officer (DPO)',
    category: 'Leadership',
    description: 'Statutory Authority under Section 8(9) & Rule 9 for DPBI and Citizen inquiries.',
    authorityLevel: 'Statutory',
    tone: 'blue',
  },
  {
    id: 'ACT-03',
    title: 'Chief Information Security Officer (CISO)',
    category: 'Leadership',
    description: 'Security Authority orchestrating IT Act 70B CERT-In 6h & DPBI 72h cyber response.',
    authorityLevel: 'Statutory',
    tone: 'indigo',
  },
  {
    id: 'ACT-04',
    title: 'Compliance Officer',
    category: 'Leadership',
    description: 'Operational compliance oversight, Section 33(2) defense file maintenance.',
    authorityLevel: 'Operational',
    tone: 'cyan',
  },
  {
    id: 'ACT-05',
    title: 'Department Head / Ward Officer',
    category: 'Operations',
    description: 'Operational head of 13 municipal departments with RLS dept-scoped access.',
    authorityLevel: 'Operational',
    tone: 'teal',
  },
  {
    id: 'ACT-06',
    title: 'Data Custodian / Field Worker',
    category: 'Operations',
    description: 'Field data entry, verification, and first-line rights fulfillment verification.',
    authorityLevel: 'Operational',
    tone: 'emerald',
  },
  {
    id: 'ACT-07',
    title: 'Privacy Analyst',
    category: 'Operations',
    description: 'DPIA evaluation (Rule 13(3)), Rule 8(2) 48h pre-erasure intimation gating.',
    authorityLevel: 'Operational',
    tone: 'green',
  },
  {
    id: 'ACT-08',
    title: 'Security Analyst',
    category: 'Operations',
    description: 'SIEM monitoring, tabletop drill simulation (SIM-DRILL-), breach triage.',
    authorityLevel: 'Operational',
    tone: 'yellow',
  },
  {
    id: 'ACT-09',
    title: 'System Owner / DBA',
    category: 'Operations',
    description: 'FIPS 140-3 HSM key custody, HMAC blind index indexing, bi-temporal schema owner.',
    authorityLevel: 'Operational',
    tone: 'amber',
  },
  {
    id: 'ACT-10',
    title: 'Data Principal (Citizen)',
    category: 'Citizen & Oversight',
    description: 'Citizen exercising Section 6 consent tracking, Section 11/12 rights, Kantara receipts.',
    authorityLevel: 'External',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    id: 'ACT-11',
    title: 'Verified Guardian (Minor VPC)',
    category: 'Citizen & Oversight',
    description: 'Parent/Guardian providing Rule 10 Verifiable Parental Consent via DigiLocker token.',
    authorityLevel: 'External',
    tone: 'orange',
  },
  {
    id: 'ACT-12',
    title: 'Authorized Nominee (Sec 14 Proxy)',
    category: 'Citizen & Oversight',
    description: 'Section 14 registered nominee exercising rights upon demise/incapacity of principal.',
    authorityLevel: 'External',
    tone: 'rose',
  },
  {
    id: 'ACT-13',
    title: 'Independent Data Auditor (Sec 10(2)(b))',
    category: 'Citizen & Oversight',
    description: 'External statutory auditor validating RoPA, Merkle log integrity, and DPA compliance.',
    authorityLevel: 'Statutory',
    tone: 'slate',
  },
  {
    id: 'ACT-14',
    title: 'DPBI Regulatory Inspector (Rule 23)',
    category: 'Citizen & Oversight',
    description: 'Data Protection Board of India statutory inspector conducting regulatory scrutiny.',
    authorityLevel: 'Statutory',
    tone: 'red',
  },
  {
    id: 'ACT-15',
    title: 'Legal Counsel / Tribunal Representative',
    category: 'Leadership',
    description: 'TDSAT Section 29 appellate dossier builder and Section 17(4) reasoned defense advocate.',
    authorityLevel: 'Statutory',
    tone: 'violet',
  },
  {
    id: 'ACT-16',
    title: 'Vendor / Processor Manager',
    category: 'Operations',
    description: 'M3 Data Processor governance, Section 8(2) and Rule 6(g) DPA clause audit.',
    authorityLevel: 'Operational',
    tone: 'sky',
  },
];
